/**
 * Helper functies om data te transformeren tussen app types en Supabase database types
 */

import type {
  Team,
  Player,
  Match,
  MatchDetails,
  Round,
  BracketGroup,
  BracketSettings,
  MatchMediaLink,
  MatchSponsor,
} from '@/app/types/bracket';

// ============================================
// Supabase Database Types (vereenvoudigd)
// ============================================

export type SupabaseTournament = {
  id: string;
  name: string;
  description?: string | null;
  bracket_type: 'single-elimination' | 'double-elimination';
  primary_color: string;
  secondary_color: string;
  background_color: string;
  bracket_style: 'classic' | 'modern' | 'playful';
  theme: 'retro' | 'futuristic' | 'sporty';
  tournament_series?: string | null;
  tournament_title?: string | null;
  tournament_description?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseTeam = {
  id: string;
  tournament_id: string;
  name: string;
  logo?: string | null;
  country_code?: string | null;
  coach?: string | null;
  founded?: string | null;
  motto?: string | null;
  twitch_link?: string | null;
  branding_logo?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type SupabasePlayer = {
  id: string;
  team_id: string;
  name: string;
  role?: string | null;
  number?: string | null;
  country_code?: string | null;
  avatar?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseBracket = {
  id: string;
  tournament_id: string;
  name: string;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseRound = {
  id: string;
  bracket_id: string;
  name: string;
  round_index: number;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseMatch = {
  id: string;
  round_id: string;
  match_index: number;
  team_a_id?: string | null;
  team_b_id?: string | null;
  team_a_score?: number | null;
  team_b_score?: number | null;
  winner_index?: number | null;
  start_time?: string | null;
  court?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseMatchDetails = {
  id: string;
  match_id: string;
  title: string;
  subtitle?: string | null;
  description?: string | null;
  featured_players?: string[] | null;
  hashtags?: string[] | null;
  prize_info?: string | null;
  schedule_note?: string | null;
  highlight_color?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type SupabaseMatchMediaLink = {
  id: string;
  match_id: string;
  platform: 'twitch' | 'youtube' | 'facebook' | 'tiktok' | 'instagram' | 'x' | 'website';
  url: string;
  label?: string | null;
  created_at?: string;
};

export type SupabaseMatchSponsor = {
  id: string;
  match_id: string;
  name: string;
  url?: string | null;
  logo?: string | null;
  created_at?: string;
};

// ============================================
// Transformers: App → Supabase
// ============================================

export function transformSettingsToTournament(
  settings: BracketSettings,
  tournamentId?: string
): Omit<SupabaseTournament, 'created_at' | 'updated_at'> {
  const result: Omit<SupabaseTournament, 'created_at' | 'updated_at'> = {
    id: tournamentId || '', // Will be generated by Supabase if empty
    name: settings.tournamentTitle || 'Untitled Tournament',
    description: settings.tournamentDescription || null,
    bracket_type: settings.bracketType,
    primary_color: settings.primaryColor,
    secondary_color: settings.secondaryColor,
    background_color: settings.backgroundColor,
    bracket_style: settings.bracketStyle,
    theme: settings.theme,
    tournament_series: settings.tournamentSeries || null,
    tournament_title: settings.tournamentTitle || null,
    tournament_description: settings.tournamentDescription || null,
  };
  
  // Only include id if provided (for updates)
  if (tournamentId) {
    result.id = tournamentId;
  }
  
  return result;
}

export function transformTeamToSupabase(
  team: Team,
  tournamentId: string
): Omit<SupabaseTeam, 'created_at' | 'updated_at'> {
  return {
    id: team.id,
    tournament_id: tournamentId,
    name: team.name,
    logo: team.logo || null,
    country_code: team.countryCode || null,
    coach: team.coach || null,
    founded: team.founded || null,
    motto: team.motto || null,
    twitch_link: team.twitchLink || null,
    branding_logo: team.brandingLogo || null,
  };
}

export function transformPlayerToSupabase(
  player: Player,
  teamId: string
): Omit<SupabasePlayer, 'created_at' | 'updated_at'> {
  return {
    id: player.id,
    team_id: teamId,
    name: player.name,
    role: player.role || null,
    number: player.number || null,
    country_code: player.countryCode || null,
    avatar: player.avatar || null,
  };
}

// ============================================
// Transformers: Supabase → App
// ============================================

export function transformTournamentToSettings(
  tournament: SupabaseTournament
): BracketSettings {
  return {
    bracketType: tournament.bracket_type,
    numTeams: 0, // Will be calculated from teams
    primaryColor: tournament.primary_color,
    secondaryColor: tournament.secondary_color,
    backgroundColor: tournament.background_color,
    bracketStyle: tournament.bracket_style,
    theme: tournament.theme,
    tournamentSeries: tournament.tournament_series || undefined,
    tournamentTitle: tournament.tournament_title || undefined,
    tournamentDescription: tournament.tournament_description || undefined,
  };
}

export function transformSupabaseToTeam(
  supabaseTeam: SupabaseTeam,
  players: SupabasePlayer[] = []
): Team {
  return {
    id: supabaseTeam.id,
    name: supabaseTeam.name,
    logo: supabaseTeam.logo || undefined,
    countryCode: supabaseTeam.country_code || undefined,
    coach: supabaseTeam.coach || undefined,
    founded: supabaseTeam.founded || undefined,
    motto: supabaseTeam.motto || undefined,
    twitchLink: supabaseTeam.twitch_link || undefined,
    brandingLogo: supabaseTeam.branding_logo || undefined,
    players: players.map(transformSupabaseToPlayer),
  };
}

export function transformSupabaseToPlayer(player: SupabasePlayer): Player {
  return {
    id: player.id,
    name: player.name,
    role: player.role || undefined,
    number: player.number || undefined,
    countryCode: player.country_code || undefined,
    avatar: player.avatar || undefined,
  };
}

export function transformSupabaseToMatchDetails(
  details: SupabaseMatchDetails,
  mediaLinks: SupabaseMatchMediaLink[] = [],
  sponsors: SupabaseMatchSponsor[] = []
): MatchDetails {
  return {
    title: details.title,
    subtitle: details.subtitle || undefined,
    description: details.description || undefined,
    featuredPlayers: details.featured_players || undefined,
    hashtags: details.hashtags || undefined,
    prizeInfo: details.prize_info || undefined,
    scheduleNote: details.schedule_note || undefined,
    highlightColor: details.highlight_color || undefined,
    streams: mediaLinks.map((link) => ({
      platform: link.platform,
      url: link.url,
      label: link.label || undefined,
    })),
    sponsors: sponsors.map((sponsor) => ({
      name: sponsor.name,
      url: sponsor.url || undefined,
      logo: sponsor.logo || undefined,
    })),
  };
}

// ============================================
// Helper: Match met teams en details samenstellen
// ============================================

export function buildMatchFromSupabase(
  match: SupabaseMatch,
  teamA: Team | null,
  teamB: Team | null,
  details?: MatchDetails
): Match {
  // Add scores to teams if they exist
  const teamAWithScore = teamA
    ? { ...teamA, score: match.team_a_score || undefined }
    : null;
  const teamBWithScore = teamB
    ? { ...teamB, score: match.team_b_score || undefined }
    : null;

  return {
    id: match.id,
    roundIndex: 0, // Will be set when building rounds
    matchIndex: match.match_index,
    teams: [teamAWithScore, teamBWithScore],
    winnerIndex: match.winner_index !== null ? match.winner_index : undefined,
    startTime: match.start_time || undefined,
    court: match.court || undefined,
    details: details,
  };
}


